// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Weeks',
      items: [
        'weeks/week-1',
        'weeks/week-2',
        'weeks/week-3',
        'weeks/week-4',
        'weeks/week-5',
        'weeks/week-6',
        'weeks/week-7',
        'weeks/week-8',
        'weeks/week-9',
        'weeks/week-10',
        'weeks/week-11',
        'weeks/week-12',
        'weeks/week-13',
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      items: [
        'modules/module-1',
        'modules/module-2',
        'modules/module-3',
        'modules/module-4',
      ],
    },
    'hardware',
    'assessments',
    'capstone',
    'resources',
    'chat-widget',
    'chat-widget-example',
    'authentication',
    'personalization-integration',
    'translation-feature',
    'translation-example',
    'subagents',
    {
      type: 'category',
      label: 'Tutorial - Basics',
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    },
    {
      type: 'category',
      label: 'Tutorial - Extras',
      items: [{type: 'autogenerated', dirName: 'tutorial-extras'}],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
